### ISSUE TITLE
测试结果实际在报错，但界面显示却是测试已通过

### ISSUE THREAD

**Issue by qingfeng** [FIRHQ/flow.ci#18]
测试失败的Log
```
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_add_contact (chat.tests.ChatTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/flow/build/borngods/gouhuo/chat/tests.py", line 19, in setUp
    self.one_user = User.create(nickname='qingfeng', avatar='347132')
  File "/home/flow/build/borngods/gouhuo/ogow/models.py", line 64, in create
    user = cls.objects.create_user(name, email, password)
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/contrib/auth/models.py", line 154, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/contrib/auth/models.py", line 148, in _create_user
    user.save(using=self._db)
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 74, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/flow/build/borngods/gouhuo/ogow/models.py", line 1065, in create_user_after_follow
    conversation_id = Conversation.add(user.id, business_user_id)
  File "/home/flow/build/borngods/gouhuo/chat/models.py", line 198, in add
    if cls.exist(user_id, contact_id):
  File "/home/flow/build/borngods/gouhuo/chat/models.py", line 174, in exist
    conversation_id = redis.hget(REDIS_CONTACT_PROFILE_KEY % user_id, contact_id)
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/redis/client.py", line 1857, in hget
    return self.execute_command('HGET', name, key)
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/flow/.pyenv/versions/2.7.11/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
```

界面显示的却是成功：
![image](https://cloud.githubusercontent.com/assets/18495/14417394/6e4197b2-ffe7-11e5-9040-07f5b58bcbaa.png)

**Comment by yunheli** [comment]
@qingfeng 已经修改了，你再试试，对您造成的不便，敬请谅解

**Comment by qingfeng** [comment]
感谢，另一个问题，测试会使用到redis，这个请问如何安装？ @yunheli

**Comment by yunheli** [comment]
在项目的 flow 中添加 plugin，在plugin list里搜索 redis 之后点击 Install ，之后 build 就启动 redis 了 @qingfeng

**Comment by qingfeng** [comment]
COOL，可以了！，另外再提一个小建议，就是手动build那个按钮，放在左边有点不太符合界面直觉，大部分action操作，都是放在描述之后的右侧，或者右下，之前用的时候，一直以为那是一个高亮的Lable区域

![image](https://cloud.githubusercontent.com/assets/18495/14449799/144d2f78-00aa-11e6-9593-99d50357fa49.png)

**Comment by qingfeng** [comment]
喔，对了，还一个问题，现在flow可以和GitHub的PR联动了吗？就是单元测试失败可以把失败状态回写到PR里？

**Comment by trawor** [comment]
@qingfeng 这个功能一直有的

![2016-04-12 12 55 48](https://cloud.githubusercontent.com/assets/72015/14450160/0e24e646-00ae-11e6-805a-a9c0d3c05dd5.jpg)

**Comment by qingfeng** [comment]
我这边没有。。。需要配置什么？

**Comment by qingfeng** [comment]
喔，我知道了，默认的flow.ci好像没有获取status权限？

**Comment by qingfeng** [comment]
配置了，但好像还是没有回写
![image](https://cloud.githubusercontent.com/assets/18495/14452074/87173828-00be-11e6-8503-7ec8fa83b9b0.png)

**Comment by trawor** [comment]
:+1:  

我把status这个问题新开了一个 issue https://github.com/FIRHQ/flow.ci/issues/20

先把当前这个问题关掉了
